### ISSUE TITLE
Possible memory leak warning

### ISSUE THREAD

**Issue by aduh95** [mdaines/viz.js#129]
I have noticed on Node.js using viz.js@2.0.0-pre.7, after processing several graph, a warning is emitted from the console:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:244:19)
    at process.addListener (events.js:262:10)
    at Module (.../node_modules/viz.js/full.js.opaque:7:1845)
    at new ModuleWrapper (.../node_modules/viz.js/viz.js:118:20)
    at new Viz (.../node_modules/viz.js/viz.js:248:24)
    ...
```

I suppose this is because the events does not get garbage collected after the diagram is rendered.

Could you remove the event listeners once used? Or [set a infinite limit](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n) on the event listener number?

**Comment by mdaines** [comment]
Can you provide an example of how you're calling Viz.js? It's possible that I'm doing something with promises that's causing uncaughtException listeners to not be removed.

**Comment by aduh95** [comment]
OK, here is a script that triggers the warning.

```js
const Viz = require("viz.js");
const { Module, render } = require("viz.js/full.js.opaque");

const renderString = (dot, vizOptions) => {
  if (!vizOptions) {
    vizOptions = { Module, render };
  }
  return new Viz(vizOptions).renderString(dot);
};

for (let i = 0; i < 15; i++) {
  renderString(`# http://www.graphviz.org/content/cluster

  digraph G {
  
      subgraph cluster_0 {
          style=filled;
          color=lightgrey;
          node [style=filled,color=white];
          a0 -> a1 -> a2 -> a3;
          label = "process #1";
      }
  
      subgraph cluster_1 {
          node [style=filled];
          b0 -> b1 -> b2 -> b3;
          label = "process #2";
          color=blue
      }
      start -> a0;
      start -> b0;
      a1 -> b3;
      b2 -> a3;
      a3 -> a0;
      a3 -> end;
      b3 -> end;
  
      start [shape=Mdiamond];
      end [shape=Msquare];
  }
  `).then(() => console.log(`Graph #${i} rendered`));
}
```

Here is the output I got:

```
$ node test.js
(node:12340) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
(node:12340) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
Graph #0 rendered
Graph #1 rendered
Graph #2 rendered
Graph #3 rendered
Graph #4 rendered
Graph #5 rendered
Graph #6 rendered
Graph #7 rendered
Graph #8 rendered
Graph #9 rendered
Graph #10 rendered
Graph #11 rendered
Graph #12 rendered
Graph #13 rendered
Graph #14 rendered
```
```

**Comment by aduh95** [comment]
Interestingly, the warning does not trigger if I re-use the same Viz object:

```js
const Viz = require("viz.js");
const { Module, render } = require("viz.js/full.js.opaque");

const viz = new Viz({ Module, render });

const renderString = (dot, vizOptions) => {
  if (!vizOptions) {
    vizOptions = { Module, render };
  }
  return viz.renderString(dot);
};

for (let i = 0; i < 15; i++) {
  renderString(`# http://www.graphviz.org/content/cluster

  digraph G${i} {
  
      subgraph cluster_0 {
          style=filled;
          color=lightgrey;
          node [style=filled,color=white];
          a0 -> a1 -> a2 -> a3;
          label = "process #1";
      }
  
      subgraph cluster_1 {
          node [style=filled];
          b0 -> b1 -> b2 -> b3;
          label = "process #2";
          color=blue
      }
      start -> a0;
      start -> b0;
      a1 -> b3;
      b2 -> a3;
      a3 -> a0;
      a3 -> end;
      b3 -> end;
  
      start [shape=Mdiamond];
      end [shape=Msquare];
  }
  `).then(() => console.log(`Graph #${i} rendered`));
}
```

The output I get:

```
$ node test.js
Graph #0 rendered
Graph #1 rendered
Graph #2 rendered
Graph #3 rendered
Graph #4 rendered
Graph #5 rendered
Graph #6 rendered
Graph #7 rendered
Graph #8 rendered
Graph #9 rendered
Graph #10 rendered
Graph #11 rendered
Graph #12 rendered
Graph #13 rendered
Graph #14 rendered
```

**Comment by AlexeyLapshin** [comment]
I think this behavior is not correct since we cannot delete an object and recreate it.

`const viz = new Viz({ Module, render });
delete viz;`

EventListener is not removed in this case, a memory leak occurs
