### ISSUE TITLE
Uncaught Assertion failed

### ISSUE THREAD

**Issue by commaster90** [mdaines/viz.js#78]
This issue happens in version 1.6.0 and above. When trying to render my graph, Chrome shows the following error.

Uncaught Assertion failed: !TREE_EDGE(e), at: ns.c,463,merge_trees at Error
    at Ga (http://localhost:8000/static/js/viz.js:48:124)
    at Fa (http://localhost:8000/static/js/viz.js:48:22)
    at ___assert_fail (http://localhost:8000/static/js/viz.js:1141:116)
    at Array.JR (http://localhost:8000/static/js/viz.js:1169:33709)
    at Object.iR [as dynCall_viiii] (http://localhost:8000/static/js/viz.js:1169:32309)
    at invoke_viiii (http://localhost:8000/static/js/viz.js:1139:160)
    at Mz (http://localhost:8000/static/js/viz.js:1161:102007)
    at Nz (http://localhost:8000/static/js/viz.js:1161:112060)
    at xh (http://localhost:8000/static/js/viz.js:1167:52541)
    at Vf (http://localhost:8000/static/js/viz.js:1158:101036)

**Comment by commaster90** [comment]
This is the dot file causing the issue. Could it be the syntax is incompatible with the newer version of Graphviz?

```txt

digraph "Template" {
  rankdir=UD
  bgcolor=transparent

0 [shape=rect style="rounded,filled" fillcolor=white label=<
  <table border="0" cellborder="0" cellpadding="0" cellspacing="3">
    <tr>
      <td width="150">
<b><font point-size="18">Start</font></b>
      </td>
    </tr>
  </table>
>]


-1 [shape=rect style="rounded,filled" fillcolor=white label=<
  <table border="0" cellborder="0" cellpadding="0" cellspacing="3">
    <tr>
      <td width="150">
<b><font point-size="18">End</font></b>
      </td>
    </tr>
  </table>
>]
{rank=sink; -1}


}
```

**Comment by mdaines** [comment]
Since this doesn't work with the regular "dot" program either (2.40.1), my guess would be that the syntax is the problem.
